default_language_version:
    python: python3.9

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.259
    hooks:
      - id: ruff
        # args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
