name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.9, '3.10']
        django-version: [2.2, 3.2, 4.0]
        exclude:
          - python-version: 3.7
            django-version: 4.0
    steps:
    # Python & dependency installation
    - uses: actions/checkout@v3
    - name: setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: pip install black ruff --pre Django==${{ matrix.django-version }}
    - name: lint with ruff
      run: ruff --format=github .
    - name: lint with black
      run: black --check honeypot
    - name: run tests
      run: django-admin test --settings=test_settings --pythonpath=.
